# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: edenramoneda
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: loyalty-coupon-lambda-api-app
# "service" is the name of this project. This will also be added to your AWS resource names.
service: loyalty-coupon-lambda-api

stages:
  default:
    params:
      tableName: "coupons-table-${sls:stage}"

provider:
  name: aws
  runtime: nodejs20.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [CouponsTable, Arn]
  environment:
    COUPONS_TABLE: ${param:tableName}

functions:
  api:
    handler: coupons.coupons
    events:
      - httpApi: "*"

resources:
  Resources:
    CouponsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: couponId
            AttributeType: S
        KeySchema:
          - AttributeName: couponId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${param:tableName}
